# Generated by Django 4.1.3 on 2023-04-10 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("teaching_hour", models.IntegerField()),
                ("is_lab", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("is_lab", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Sem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("teaching_hour", models.IntegerField()),
                (
                    "subject_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="sem_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="timetable.sem"
            ),
        ),
    ]
