# Generated by Django 4.0.2 on 2023-04-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_lab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('teaching_hour', models.IntegerField()),
                ('is_lab', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.sem')),
            ],
        ),
    ]
